vibedebug_chat:
    path: /_vibedebug/chat/{agent}/{token}
    methods: [POST]
    controller: vibedebug.controller::chat


vibedebug_prompt:
    path: /_vibedebug/{token}/prompt
    methods: [GET]
    controller: vibedebug.controller::prompt
